PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX lovvoc: <http://example.org/lovvoc#>


select distinct ?dataset ?detector ?implementation where {
  ?Concept a qb:Observation ;
	qb:dataSet ?dataset ;
	lovvoc:detector ?detector ;
	lovvoc:implementation ?implementation .
}

