PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX lovvoc: <http://example.org/lovvoc#>


select distinct ?type ?detector (count(?detector) as ?detectorCount) where {
  ?Concept a qb:Observation ;
	lovvoc:restriction-type ?type;
	lovvoc:detector ?detector ;
	lovvoc:amount ?amount .
  FILTER (?amount > 0)
} group by ?type ?detector

