PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX lovvoc: <http://example.org/lovvoc#>


select distinct ?dataset (datatype(?output) as ?datatype) where {
  ?Concept a qb:Observation ;
	lovvoc:detector ?detector ;
	?measurePredicate ?output .
  {
	select distinct ?measurePredicate where {
  	lovvoc:lovstats2018datastructure a qb:DataStructureDefinition ;
    	qb:component [
      	qb:measure ?measurePredicate
    	] .
	}
  }
}

